### PR TITLE
Allow running contoller manager only on masters

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by bn222** [comment]
@pliurh

**Comment by bn222** [comment]
@zshi-redhat

**Comment by pliurh** [comment]
We need to update the operator bundle files with `make bundle`.

**Comment by bn222** [comment]
@pliurh PTAL

**Comment by wizhaoredhat** [comment]
@bn222 I think you have overlapping branches.

**Comment by bn222** [comment]
@pliurh PTAL

**Comment by pliurh** [comment]
@bn222 It looks good to me. But you need to rebase the PR.

**Pull request merged**
