### PR TITLE
Bug 2090549: add amd64 label

### PR DESCRIPTION
**Pull request by zshi-redhat**
Allow operator to run on amd arch in hypershift management cluster

### CODE REVIEW

**Comment by yselkowitz** [comment]
nack.  removing the label will cause the operator to be shown only on x86.  if you want this available for all arches, first the image must be built for all arches, then labels for all arches must be added.
/hold

**Comment by zshi-redhat** [comment]
> nack. removing the label will cause the operator to be shown only on x86. if you want this available for all arches, first the image must be built for all arches, then labels for all arches must be added. /hold

@yselkowitz how shall I enable the operator image builkd on x86?

**Comment by yselkowitz** [comment]
due to a bug in ART tooling it is currently being built for x86 and arm even though only arm was  the initial target.

**Comment by zshi-redhat** [comment]
> due to a bug in ART tooling it is currently being built for x86 and arm even though only arm was the initial target.

Do I need to make a request to enable x86 image?

**Comment by yselkowitz** [comment]
Let's back up for a moment.  What exactly do you want to support that isn't already?

**Comment by zshi-redhat** [comment]
> Let's back up for a moment. What exactly do you want to support that isn't already?

To support running dpu-network-operator in hypershift management cluster, which could be x86 arch.

**Comment by yselkowitz** [comment]
So iow you want to be able to run this operator on x86 or arm?  Are ppc64le/s390x needed too?

If this is limited to x86 and arm, then nothing needs to be changed on the image build side, and here we need to *add* the `arch.amd64` label.  If other arches are needed, then we have to adjust the build first.

**Comment by zshi-redhat** [comment]
> So iow you want to be able to run this operator on x86 or arm? Are ppc64le/s390x needed too?
> 
> If this is limited to x86 and arm, then nothing needs to be changed on the image build side, and here we need to _add_ the `arch.amd64` label. If other arches are needed, then we have to adjust the build first.

Yes, only x86 is needed for now.

**Comment by bn222** [comment]
> > So iow you want to be able to run this operator on x86 or arm? Are ppc64le/s390x needed too?
> > If this is limited to x86 and arm, then nothing needs to be changed on the image build side, and here we need to _add_ the `arch.amd64` label. If other arches are needed, then we have to adjust the build first.
> 
> Yes, only x86 is needed for now.

we need both arm and x86, no?

**Comment by yselkowitz** [comment]
> right, both arm and x86. arm is available now, we just need to enable x86.

In that case, instead of removing all labels here, *keep* the arm64 label and *add* the label for amd64.

**Comment by zshi-redhat** [comment]
> > right, both arm and x86. arm is available now, we just need to enable x86.
> 
> In that case, instead of removing all labels here, _keep_ the arm64 label and _add_ the label for amd64.

updated to add amd4 label.

**Pull request merged**
